# SPDX-License-Identifier: MIT-0
---
# tasks file for web_olympic_games
- name: "Web Olympic Games | Create the web directory"
  become: true
  ansible.builtin.file:
    path: "/var/www/html/{{ web_olympic_games_app_name }}"
    state: directory
    owner: "{{ web_olympic_games_app_user }}"
    group: "{{ web_olympic_games_app_group }}"
    mode: '0755'

- name: "Web Olympic Games | Copy the web content from files"
  become: true
  ansible.builtin.copy:
    src: "{{ role_path }}/files/{{ web_olympic_games_app_name }}/"
    dest: "/var/www/html/{{ web_olympic_games_app_name }}/"
    owner: "{{ web_olympic_games_app_user }}"
    group: "{{ web_olympic_games_app_group }}"
    mode: "0755"
  notify: "reload nginx"
