# SPDX-License-Identifier: MIT-0
---
# defaults file for web_olympic_games
web_olympic_games_app_user: "www-data"
web_olympic_games_app_group: "www-data"
web_olympic_games_app_name: "olympic-games-starter"
