variable "my_pc_public_ip" {
  description = "Public IP address of the machine from which you will connect to the AWS instance. This variable is used to restrict SSH access to the instance to only your machine."
  type        = string
  sensitive = true
  default     = ""
}

variable "generated_key_name" {
  type        = string
  default     = "openclassrooms_edo_p5"
  description = "Key-pair generated by Terraform"
}
